kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install numpy
  - pip install python-math

- name: testing
  image: python
  commands:
  - python --version

- name: greeting
  image: python
  commands:
  - python ./hello.py

- name: translator
  image: python
  commands:
  - python ./translator.py
